#!/bin/bash
# Installation et vérification WebSocket

echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║                 WEBSOCKET MESSAGING - GUIDE D'INSTALLATION                    ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 FICHIERS MODIFIÉS ET CRÉÉS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKEND:"
echo "  ⭐ app/Events/MessageSent.php"
echo "     → Événement dispatché lors de la création d'un message"
echo "     → Contient la clé de conversation et les données à diffuser"
echo ""
echo "  ⭐ routes/channels.php"
echo "     → Définit les canaux privés pour les conversations"
echo "     → Valide l'accès au canal (les deux participants)"
echo ""
echo "  ✏️  app/Models/Messages.php"
echo "     → Ajout de l'import MessageSent"
echo "     → Le modèle dispatch l'événement à la création"
echo ""
echo "  ⚙️  .env.example"
echo "     → Ajout des variables Reverb"
echo ""

echo "FRONTEND:"
echo "  ⭐ src/services/websocket.js"
echo "     → Gestion complète de la connexion WebSocket"
echo "     → Initialisation Echo, abonnement aux canaux"
echo "     → Reconnexion automatique"
echo ""
echo "  ⭐ src/composables/useChat.js"
echo "     → Logique métier complète"
echo "     → Envoi, réception, marquage des messages"
echo "     → Gestion des conversations"
echo ""
echo "  ⭐ src/config/websocket.js"
echo "     → Configuration centralisée"
echo "     → Variables d'environnement"
echo ""
echo "  ⚙️  .env.example"
echo "     → Ajout des variables Reverb"
echo ""

echo "DOCUMENTATION:"
echo "  📚 WEBSOCKET_SETUP.md"
echo "     → Guide complet d'utilisation et de configuration"
echo ""
echo "  📝 INTEGRATION_GUIDE.js"
echo "     → Exemple d'intégration dans un composant Vue"
echo ""
echo "  🔧 TROUBLESHOOTING.md"
echo "     → Dépannage et solutions aux problèmes courants"
echo ""
echo "  📖 WEBSOCKET_IMPLEMENTATION.md"
echo "     → Vue d'ensemble de l'implémentation"
echo ""
echo "  🚀 setup-websocket.sh"
echo "     → Script d'aide pour la configuration"
echo ""
echo "  🧪 tests/Feature/MessageBroadcastingTest.php"
echo "     → Suite de tests complets"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🚀 DÉMARRAGE RAPIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  BACKEND"
echo "  cd backend"
echo "  cp .env.example .env"
echo "  composer install"
echo "  php artisan key:generate"
echo "  # Configurer la base de données dans .env"
echo "  php artisan migrate"
echo "  php artisan serve              # Terminal 1"
echo "  php artisan reverb:start      # Terminal 2"
echo ""

echo "2️⃣  FRONTEND"
echo "  cd frontend"
echo "  cp .env.example .env.local"
echo "  npm install"
echo "  npm install laravel-echo pusher-js"
echo "  npm run dev"
echo ""

echo "3️⃣  TEST"
echo "  → Ouvrez http://localhost:5173"
echo "  → Connectez-vous avec deux utilisateurs différents"
echo "  → Allez à Messages dans les deux onglets"
echo "  → Envoyez un message - il devrait arriver instantanément"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ VÉRIFICATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Terminal Reverb:"
echo "  ✓ [HH:MM:SS] User X connected"
echo "  ✓ [HH:MM:SS] User Y subscribed to chat.X_Y"
echo "  ✓ [HH:MM:SS] Broadcast to chat.X_Y"
echo ""
echo "Console navigateur (F12):"
echo "  ✓ ✓ WebSocket connecté"
echo "  ✓ S'abonner à la conversation: chat.X_Y"
echo "  ✓ Message reçu: { id, content, sender, ... }"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Lire WEBSOCKET_SETUP.md pour la configuration complète"
echo "  2. Consulter INTEGRATION_GUIDE.js pour l'exemple d'intégration"
echo "  3. Vérifier TROUBLESHOOTING.md en cas de problème"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🎯 FONCTIONNALITÉS IMPLÉMENTÉES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✅ Envoi/réception en temps réel via WebSocket"
echo "  ✅ Canaux privés pour les conversations"
echo "  ✅ Marquage des messages comme lus"
echo "  ✅ Historique des conversations"
echo "  ✅ Support des pièces jointes"
echo "  ✅ Reconnexion automatique"
echo "  ✅ Synchronisation multi-navigateur"
echo "  ✅ Authentification sécurisée (Sanctum)"
echo "  ✅ Tests unitaires complets"
echo "  ✅ Documentation complète"
echo ""

echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║           ✨ IMPLÉMENTATION WEBSOCKET COMPLÈTE ET OPÉRATIONNELLE! ✨          ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"
echo ""

