#!/bin/bash
# Script de configuration du projet avec WebSocket

echo "======================================"
echo "Configuration WebSocket - Chat Application"
echo "======================================"
echo ""

# Configuration Backend
echo "1️⃣  Configuration Backend (Laravel + Reverb)"
echo "================================================"
echo ""
echo "✓ Vérifiez que vous avez copié .env.example à .env:"
echo "  cp backend/.env.example backend/.env"
echo ""
echo "✓ Installez les dépendances:"
echo "  cd backend"
echo "  composer install"
echo ""
echo "✓ Générez la clé d'application:"
echo "  php artisan key:generate"
echo ""
echo "✓ Exécutez les migrations:"
echo "  php artisan migrate"
echo ""
echo "✓ Configurez BROADCAST_CONNECTION=reverb dans .env"
echo ""
echo "✓ Démarrez le serveur Reverb:"
echo "  php artisan reverb:start"
echo "  # Ou avec SSL:"
echo "  php artisan reverb:start --host=0.0.0.0 --port=8443 --scheme=https"
echo ""
echo "✓ (Optionnel) Démarrez le serveur Laravel:"
echo "  php artisan serve"
echo ""

# Configuration Frontend
echo ""
echo "2️⃣  Configuration Frontend (Vue 3 + Echo)"
echo "=========================================="
echo ""
echo "✓ Vérifiez que vous avez copié .env.example à .env.local:"
echo "  cp frontend/.env.example frontend/.env.local"
echo ""
echo "✓ Configurez les variables d'environnement:"
echo "  VITE_API_URL=http://localhost:8000"
echo "  VITE_REVERB_APP_KEY=app-key"
echo "  VITE_REVERB_HOST=localhost"
echo "  VITE_REVERB_PORT=8080"
echo ""
echo "✓ Installez les dépendances:"
echo "  cd frontend"
echo "  npm install"
echo ""
echo "✓ Assurez-vous que laravel-echo et pusher-js sont installés:"
echo "  npm install laravel-echo pusher-js"
echo ""
echo "✓ Démarrez le serveur de développement:"
echo "  npm run dev"
echo ""

# Tests
echo ""
echo "3️⃣  Tests et Vérification"
echo "=========================="
echo ""
echo "✓ Vérifiez la connexion WebSocket:"
echo "  1. Ouvrez http://localhost:5173 (ou le port de votre app)"
echo "  2. Ouvrez la console (F12)"
echo "  3. Connectez-vous"
echo "  4. Allez à la section Messages"
echo "  5. Cherchez 'WebSocket connecté' dans la console"
echo ""
echo "✓ Testez l'envoi de messages:"
echo "  1. Ouvrez deux navigateurs/onglets différents"
echo "  2. Connectez-vous avec deux utilisateurs différents"
echo "  3. Allez aux Messages dans les deux"
echo "  4. Sélectionnez une conversation"
echo "  5. Envoyez un message d'un côté"
echo "  6. Vérifiez que le message apparaît instantanément de l'autre côté"
echo ""

# Architecture
echo ""
echo "4️⃣  Architecture"
echo "==============="
echo ""
echo "Backend:"
echo "  - Event: app/Events/MessageSent.php"
echo "  - Channel: routes/channels.php (chat.{conversationKey})"
echo "  - Config: config/broadcasting.php (Reverb)"
echo "  - Model: app/Models/Messages.php (dispatch MessageSent)"
echo ""
echo "Frontend:"
echo "  - Service: src/services/websocket.js (Echo, connexion)"
echo "  - Composable: src/composables/useChat.js (logique métier)"
echo "  - Config: src/config/websocket.js (env variables)"
echo ""

echo ""
echo "======================================"
echo "Configuration terminée! ✓"
echo "======================================"
echo ""
echo "Ressources:"
echo "  📚 WEBSOCKET_SETUP.md - Guide complet"
echo "  📝 INTEGRATION_GUIDE.js - Exemple d'intégration"
echo ""
